config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'


  resources :books, only:[:index,:show,:edit,:create,:destroy,:update]

  resources :users, only:[:index,:show,:edit,:update]

  get '/home/about' => 'homes#about'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,length: { minimum: 1, maximum: 200 }
 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :image

  has_one_attached :profile_image


  validates :name, presence: true, uniqueness: true,length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }



  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image2.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top,:about]

  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end



  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :is_matching_login_user, only: [:edit]


  def index
    @book = Book.new
    @books = Book.all
    @user = @book.user
    

  end

  def show
    @book = Book.find(params[:id])
    @books = Book.all
    @user = @book.user
    @new_book = Book.new

  end

  def edit
    is_matching_login_user
    @book = Book.find(params[:id])
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id),notice:'You have updated user successfully.'
    else
    render :edit
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     redirect_to book_path(@book.id), notice:'You have created book successfully.'
    else
      @books = Book.all
     render :index
    end
  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image2.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end




end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :is_matching_login_user, only: [ :update]
  before_action :is_matching_login_user_edit, only: [ :edit]



  def index
    @book = Book.new
    @books = Book.all
    @user = @book.user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update

    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(current_user.id),notice:'You have updated user successfully.'
    else
      render :edit
    end
  end


   private

   def user_params
     params.require(:user).permit(:name, :email, :password, :introduction, :profile_image)
   end


  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

  def is_matching_login_user_edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>


       <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
     　　<ul>
    　　<% @book.errors.full_messages.each do |message| %>
      　<li><%= message %></li>
    　　<% end %>
    　　</ul>
    　 <% end %>




      <%= form_with model: @book do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label><br>
        <%= f.text_field :title, autofocus: true, id:"book_title" %>
       </div>

       <div class="form-group">
         <label for="book_body">Opinion</label><br>
         <%= f.text_area :body, autofocus: true, id:"book_body" %>
       </div>

       <div class="form-group">
       <%= f.submit "Update Book",class: 'btn btn-success' %>
       </div>

        <% end %>

        <%= link_to "Show",book_path(@book.id) %>｜<%= link_to "Back",books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<main>

  <div class="container px-5 px-sm-0">

     <% if @book.errors.any? %>
    <h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
     <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
    <% end %>

    <div class="row">



      <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag current_user.get_profile_image(100,100) %>

        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= current_user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= current_user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(current_user.id),class: 'btn btn-outline-secondary btn-block' do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </div>

        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book do |f| %>
         <div class="form-group">
           <label for="book_title">Title</label>
            <%= f.text_field :title ,class: "form-control" %>
         </div>
         <div class="form-group">
           <label for="book_option">Opinion</label>
            <%= f.text_area :body ,class: "form-control" %>
         </div>
         <div class="form-group">
           <%= f.submit'Create Book',class: "btn btn-success" %>
         </div>
         <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
            <thead>
               <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
               </tr>
            </thead>
            <% @books.each do |book| %>
            <tbody>
              <tr>
                <td><%= link_to user_path(book.user_id) do  %>
                <%= image_tag book.user.get_profile_image(100,100) %>
                <% end %></td>
                <td><%= link_to book.title,book_path(book.id) %></td>
                <td><%= book.body %></td>
              </tr>
            </tbody>
            <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>

  <div class="container px-5 px-sm-0">
    <div class="row">

     <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag @user.get_profile_image(100,100) %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user.id),class: 'btn btn-outline-secondary btn-block' do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </div>
        


        <h2 class="mt-3">New book</h2>
        <%= form_with model: @new_book do |f| %>
         <div class="form-group">
           <label for="book_title">Title</label>
            <%= f.text_field :title ,class: "form-control" %>
         </div>
         <div class="form-group">
           <label for="book_option">Opinion</label>
            <%= f.text_area :body ,class: "form-control" %>
         </div>
         <div class="form-group">
           <%= f.submit'Create Book',class: "btn btn-success" %>
         </div>
         <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <thead>
               <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
               </tr>
            </thead>
          <tbody>
            <tr>
              <td><%= image_tag @user.get_profile_image(100,100) %><br><%= link_to @user.name ,user_path(@book.user.id) %></td>
              <td><%= link_to @book.title ,book_path(@book.id) %></td>
              <td><%= @book.body %></td>
              <td>
                <% if @user == current_user %>
                <%= link_to edit_book_path(@book.id) ,class: 'btn btn-sm btn-success' do  %>
                Edit
                <% end %>
                <% end %>
              </td>
              <td>
                 <% if @book.user == current_user %>
                  <%= link_to "Destroy", book_path(@book), method: :delete,"data-confirm" => "本当に消しますか？",class: 'btn btn-sm btn-danger' %>
                 <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>

  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcom to <i class="fas fa-book"></i><strong>Bookers!</strong></h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>

<div class="container">
  <div class="row">
   <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>
      welcome to <i class="fas fa-book"></i>Bookers !!
    </h1>
    <p>In<i class="fas fa-book"></i><strong>Bookers,</strong></p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p>about various books!</p>
    <div class="btn-wrapper col-10 mx-auto">
      <div class="row">
        <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
      </div>
      <div class="row">
        <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
      </div>
    </div>
   </div>
  </div>
</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/2729495828.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
       <a class="navbar-brand" href="/"> <span>Bookers</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
           <li>
            <%= link_to  user_path(current_user.id), class: 'nav-link text-light' do  %>
            <i class="fas fa-home"></i> Home
            <% end %>
           </li>
           <li>
            <%= link_to  users_path, class: 'nav-link text-light' do %>
            <i class="fas fa-users"></i> Users
            <% end %>
           </li>
           <li>
            <%= link_to books_path, class: 'nav-link text-light' do %>
            <i class="fas fa-book-open"></i> Books
            <% end %>
           </li>
           <li>
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
            <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
           </li>

          <% else %>
           <li>
            <a class="nav-link text-light" href="/"><i class="fas fa-home"></i> Home</a>
           </li>
           <li>
             <%= link_to home_about_path, class: 'nav-link text-light' do %>
             <i class="fas fa-link"></i> About
             <% end %>
           </li>
           <li>
             <a class="nav-link text-light" href="/users/sign_up"><i class="fas fa-user-plus"></i> Sign up</a>
           </li>
           <li>
             <a class="nav-link text-light" href= "/users/sign_in"><i class="fas fa-sign-in-alt"></i> Log in</a>
           </li>

          <% end %>
         </ul>
        </div>
      </div>
     </nav>
    </header>


    <% flash.each do |key, value| %>
     <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>




    <%= yield %>



    <footer>
      <div class = "container mt-5">
        <div class = "row">
         <div class = "mx-auto">
          <p>CopyRight Infratop.inc</p>
         </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>


       <% if @user.errors.any? %>
       <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
        <ul>
         <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
       <% end %>



      <%= form_with model: @user do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label><br>
        <%= f.text_field :name, autofocus: true, id: "user_name" %>
       </div>

      <div class="form-group">
        <label for="user_image">Image</label><br>
        <%= f.file_field :profile_image, placeholder: "user_image", accept: "image/*" %>
       </div>

       <div class="form-group">
         <label for="user_introduction">Introduction</label><br>
         <%= f.text_area :introduction, autofocus: true, id: "user_introduction" %>
       </div>

       <div class="form-group">
       <%= f.submit "Update User",class: 'btn btn-secondary' %>
       </div>

        <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<main>

  <div class="container px-5 px-sm-0">
    <div class="row">

      <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag current_user.get_profile_image(100,100) %>

        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= current_user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= current_user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(current_user.id),class: 'btn btn-outline-secondary btn-block' do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </div>

        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book do |f| %>
         <div class="form-group">
           <label for="book_title">Title</label>
            <%= f.text_field :title ,class: "form-control" %>
         </div>
         <div class="form-group">
           <label for="book_option">Option</label>
            <%= f.text_area :body ,class: "form-control" %>
         </div>
         <div class="form-group">
           <%= f.submit'Create Book',class: "btn btn-success" %>
         </div>
         <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
            <thead>
               <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
               </tr>
            </thead>
            <% @users.each do |user| %>
            <tbody>
              <tr>
                <td><%= image_tag user.get_profile_image(100,100) %></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id) %></td>
              </tr>
            </tbody>
            <% end %>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>

  <div class="container px-5 px-sm-0">
    <div class="row">

      <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag @user.get_profile_image(100,100) %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to edit_user_path(@user.id),class: 'btn btn-outline-secondary btn-block' do %>
          <i class="fas fa-user-cog"></i>
          <% end %>
        </div>


        <h2 class="mt-3">New book</h2>
        <%= form_with model: @book do |f| %>
         <div class="form-group">
           <label for="book_title">Title</label>
            <%= f.text_field :title ,class: "form-control" %>
         </div>
         <div class="form-group">
           <label for="book_option">Opinion</label>
            <%= f.text_area :body ,class: "form-control" %>
         </div>
         <div class="form-group">
           <%= f.submit'Create Book',class: "btn btn-success" %>
         </div>
         <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
            <thead>
               <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
               </tr>
            </thead>
            <% @books.each do |book| %>
            <tbody>
              <tr>

                <td><%= link_to user_path(book.user_id) do  %>
                <%= image_tag @user.get_profile_image(100,100) %>
                <% end %></td>
                <td><%= link_to book.title,book_path(book.id) %></td>
                <td><%= book.body %></td>

              </tr>
            </tbody>
            <% end %>
        </table>
      </div>
    </div>
  </div>
</main>